// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web — '
        'run FlutterFire CLI again and include web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos — '
          'run FlutterFire CLI again and include macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows — '
          'run FlutterFire CLI again and include windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux — '
          'run FlutterFire CLI again and include linux.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSbA12Bn9HKpi2g3CJ4Ub1l497lChkaPU',
    appId: '1:700093511102:android:e1fc4be3ce4facfcc0f5ef',
    messagingSenderId: '700093511102',
    projectId: 'cardex-8f893',
    storageBucket: 'cardex-8f893.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwas6Q5xY5SGdpeaiErp8XH-9BsDJhsts',
    appId: '1:700093511102:ios:f6ac6809314ad76ec0f5ef',
    messagingSenderId: '700093511102',
    projectId: 'cardex-8f893',
    storageBucket: 'cardex-8f893.firebasestorage.app',
    iosBundleId: 'com.example.carDataApp',
  );
}
